# Generated by Django 5.1.5 on 2025-01-23 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_user_is_active_user_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
    ]
